name: cached-build

on:
  pull_request:

jobs:
  cached-build:
    name: Nix build using GitHub action cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Nix post-build-hook
      run: |
        # https://nixos.org/manual/nix/stable/#idm140737321149104
        (
        cat <<'EOF'
        #!/bin/sh
        set -euf
        export IFS=' '

        echo "DRV_PATH  = $DRV_PATH"
        echo "OUT_PATHS = $OUT_PATHS"

        mkdir -p /tmp/cache

        echo "$DRV_PATH" >>/tmp/cache/paths
        for p in "$OUT_PATHS"; do
          echo "$p" >>/tmp/cache/paths
        done

        exec /nix/var/nix/profiles/default/bin/nix copy --to file:///tmp/cache $OUT_PATHS
        EOF
        ) >/tmp/nix-cache.sh
        chmod +x /tmp/nix-cache.sh

    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.9/install
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          substituters = https://hydra.iohk.io
          post-build-hook = /tmp/nix-cache.sh

    - uses: actions/cache@v2
      id: cache
      env:
        cache-name: cached-build-v1
      with:
        path: /tmp/cache
        key: ${{ env.cache-name }}-${{ hashFiles('*.nix') }} }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Restore from Nix cache
      if: steps.cache.outputs.cache-hit == 'true'
      run: xargs nix copy --from file:///tmp/cache </tmp/cache/paths

    - run: nix-build nixpkgs.nix -A hello
